version: '3.8'
services:
  dst-server:
    image: jamesits/dst-server:latest
    restart: "on-failure:5"
    ports:
      - "10999-11000:10999-11000/udp"
      - "12346-12347:12346-12347/udp"
    volumes:
      - ${pwd}/data:/data